name: Mountcook
favicon: null
layout_spectrum: 0.19760193396359682
typography_spectrum: 0.04490037355571985
title: MountCook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3548784682061523
  lightness: 0.6188564531039447
  saturation: 0.3579315028619021
  rhythmicContrast: 0.5436674789525568
purpose: []
